server {
    listen 80;
    server_name ttsmaintenance.com www.ttsmaintenance.com;
    return 301 https://$host$request_uri;
}

server {
    listen 443 ssl;
    server_name ttsmaintenance.com www.ttsmaintenance.com;

    ssl_certificate     /etc/nginx/ssl/live/ttsmaintenance.com/fullchain.pem;
    ssl_certificate_key /etc/nginx/ssl/live/ttsmaintenance.com/privkey.pem;
    ssl_protocols       TLSv1.2 TLSv1.3;
    ssl_ciphers         HIGH:!aNULL:!MD5;
    ssl_prefer_server_ciphers on;

    root /usr/share/nginx/html;
    index index.html;

    client_max_body_size 100M;

    location /api/qrcodes/showqr/ {
        proxy_pass http://backend:3000/qrcodes/showqr/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
    }

    location /api/ {
        client_max_body_size 100M;
        proxy_pass http://backend:3000/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        proxy_set_header X-Real-IP $remote_addr;
        proxy_set_header X-Forwarded-For $proxy_add_x_forwarded_for;
        proxy_read_timeout 300s;
        proxy_send_timeout 300s;
    }

    location /uploads/ {
        alias /home/adminsys/TTSmaintenance/backend/uploads/;
        add_header Access-Control-Allow-Origin *;
        expires 30d;
    }

    location /RessourcesPDF/ {
        proxy_pass http://backend:3000/RessourcesPDF/;
        proxy_http_version 1.1;
        proxy_set_header Host $host;
        expires 30d;
    }

    location /SiteDetails/ {
        try_files $uri /SiteDetails/siteDetails.html;
    }
    location /ProduitDetails/ {
        try_files $uri /ProduitDetails/produitDetails.html;
    }
    location /ClientDetails/ {
        try_files $uri /ClientDetails/clientDetails.html;
    }
    location /MaintenanceDetails/ {
        try_files $uri /MaintenanceDetails/MaintenanceDetails.html;
    }

    location / {
        try_files $uri $uri/ /index.html;
    }
}